apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipa-pj-worker
  namespace: ipa2025
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipa-pj-worker
  template:
    metadata:
      labels:
        app: ipa-pj-worker
    spec:
      containers:
        - name: ipa-pj-worker
          image: romieohm/worker:latest
          env:
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: ipa-pj-secret
                  key: username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: ipa-pj-secret
                  key: password
