apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ipa-pj-worker-scaler
  namespace: ipa2025
spec:
  scaleTargetRef:
    name: ipa-pj-worker
  pollingInterval: 15
  cooldownPeriod: 120
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: rabbitmq
      metadata:
        queueName: router_jobs
        mode: QueueLength
        value: "10"
        protocol: auto
        hostFromEnv: RABBIT_HOST
        usernameFromEnv: RABBITMQ_DEFAULT_USER
        passwordFromEnv: RABBITMQ_DEFAULT_PASS