apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ipa-pj-scaler
  namespace: ipa2025
spec:
  scaleTargetRef:
    kind: Deployment
    name: ipa-pj-consumer
  pollingInterval: 15
  cooldownPeriod: 120
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: rabbitmq
      metadata:
        hostFromEnv: RABBIT_HOST
        queueName: router_jobs
        mode: QueueLength
        value: "10"
        protocol: auto